### ISSUE TITLE
Empirical Analysis on the Commonsense KG Encoder

### ISSUE THREAD

**Issue by jw9603** [RUCAIBox/SAFE#2]
Hello,

I am interested in reproducing the empirical analysis on the commonsense kg encoder. I looked at the code and had a quick question

1. What code did you experiment with fig1 and fig2?

Thank you so much for taking the time out of your busy schedule.

**Comment by JBoRu** [comment]
Hi,
   The code for producing fig1 and fig2 is based on this repo. For fig1, you just need to drop the specific module to control the ablation study. For fig2, you should preprocess the data to get the corresponding training data.

**Comment by jw9603** [comment]
Thank you for replying my questions
