### ISSUE TITLE
How to know other node's text information?

### ISSUE THREAD

**Issue by jw9603** [RUCAIBox/SAFE#3]
Hello,
Thank you for providing such an excellent paper.
I am a student with a lot of interest in this field. I know that the OpenBookQA dataset has 4 correct labels per question, and accordingly, 4 subgraphs occur.
Here, each subgraph has 200 nodes.
There are three types of nodes: context, question, answer, and other nodes. What is the way to know the text information of other nodes? Thanks for reading the long question. have a good day.

**Comment by JBoRu** [comment]
Hi,
Thanks for your attention! I'm sorry that I can't fully understand your question. Given a question and four candidate options, we extract the concepts in the question and options. Then, we can extract a subgraph for each option based on the concepts in ConceptNet. In the subgraph, the concepts in question are *question nodes*, the concepts in answer are *answer nodes*, the other concepts between question nodes and answer nodes are *other nodes* (e.g., the nodes in the shortest paths from question ndoes to answer ndoes).

**Comment by jw9603** [comment]
I think there must have been a misunderstanding in my words. Let me give you an example.
The question is:
Question:
“A person wants to start saving money so that they can afford a nice vacation at the end of the year. After looking over their budget and expenses, they decide the best way to save money is to”

Answer:
A. make more phone calls
B. quit eating lunch out
C. buy less with monopoly money 
D. have lunch with friends

In the above problem
"qc" : ["afford", "best", "best_way", "budget", "decide", "end", "expense", "expenses", "good", "look", "looking", " money", "nice", "nice_vacation", "person", "person_wants", "save", "save_money", "saving", "saving_money", "start", "us_budget", "vacation", "way" , "year"],
"ac": ["call", "calls", "phone", "phone_call", "phone_calls"]}
It is configured like this, and the context node is known as the node connecting the question and answer nodes.
What I'm curious about in this situation is how to check(know) which words the other nodes are embedded with.
Thank you for the reply.

**Comment by JBoRu** [comment]
You are right! And the context nodes are the other nodes in my work. You can see our node definition in Sec 4.1 of our SAFE paper. We only define three types of nodes: question node, answer node, other node.

**Comment by jw9603** [comment]
I was just looking at the code and there was a misunderstanding.
If so, can we know the text that matches other nodes except the context node?
Thank you so much for your reply.

**Comment by JBoRu** [comment]
Sorry, I don't have any valid idea about constructing the text matching other nodes.  On possible way is to extract the text containing the other nodes from existing web corpus such as C4, Wikipedia (or the text corpus for constructing ConceptNet). But i think it's not a elegant solution.

**Comment by jw9603** [comment]
Thank you. Have a good day
