### ISSUE TITLE
question about running time

### ISSUE THREAD

**Issue by sana-mine** [RUCAIBox/SAFE#4]
Hello, I am very interested in your work. I would like to ask about the running time and GPU memory of your model on commenseQA dataset.

**Comment by JBoRu** [comment]
Hi, thanks for your attention. In my impression, the running time is approximately the same as directly using the Roberta to predict answers since our SAFE module just contains some MLP layers. And the GPU memory at least needs 12G. Welcome to using SAFE as the baseline.

**Comment by sana-mine** [comment]
Thanks for your reply!
But I also find a question.When I went to the function gound() in preprocessing, I found that the progress bar of tqdm was always 0. Then I find that it was always stuck in the function load_matcher()  during debugging. Do you know how to solve it?
![image](https://github.com/RUCAIBox/SAFE/assets/78332751/221f4626-9183-4a8b-b81c-6f36f1902827)
![image](https://github.com/RUCAIBox/SAFE/assets/78332751/e25d62d2-99b6-4211-b6b9-9046f6e91a84)

**Comment by sana-mine** [comment]
> Thanks for your reply! But I also find a question.When I went to the function gound() in preprocessing, I found that the progress bar of tqdm was always 0. Then I find that it was always stuck in the function load_matcher() during debugging. Do you know how to solve it? ![image](https://user-images.githubusercontent.com/78332751/239715814-221f4626-9183-4a8b-b81c-6f36f1902827.png) ![image](https://user-images.githubusercontent.com/78332751/239715826-e25d62d2-99b6-4211-b6b9-9046f6e91a84.png)

Ihave solved it. The problem is that I set too many processes.
